apiVersion: v1
kind: Template
labels:
  template: GLPI
metadata:
 name: GLPI
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 80
    selector:
      app: "${LABEL}"
      deploymentconfig: "${NAME}"
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${NAME}"
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
    annotations:  
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: "Recreate"
    triggers: 
    - imageChangeParams:
        automatic: false
        containerNames:
          - "${NAME}"
        from:
          kind: ImageStreamTag
          name: 'docker-glpi:latest'
          namespace: statefulset-test
      type: ImageChange
    replicas: 1
    selector:
      app: "${LABEL}"
      deploymentconfig: "${NAME}"
    template:
      metadata:
        labels:
          app: "${LABEL}"
          deploymentconfig: "${NAME}"
      spec:
        containers:
        - image: " "
          imagePullPolicy: Always
          name: "${NAME}"
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/glpi
              name: glpi-data
        volumes:
          - name: glpi-data
            persistentVolumeClaim:
              claimName: glpi-data
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
- name: LABEL
  displayName: App label
  required: true
  #value: marketing-management-v1
