apiVersion: v1
kind: Template
labels:
  template: GLPI
metadata:
 name: GLPI
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 80
    selector:
      app: "${LABEL}"
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: "${LABEL}"
    name: "${NAME}"
  spec:
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${NAME}"
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: "${NAME}"
    labels:
      app: "${LABEL}"
  spec:
    serviceName: "${NAME}"
    replicas: 1
    selector:
      matchLabels:
        app: "${LABEL}"
    template:
      metadata:
        labels:
          app: "${LABEL}"
      spec:
        containers:
        - name: "${NAME}"
          image: " "
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/www/glpi
              name: glpi-data
          ports:
            - containerPort: 80
              protocol: TCP
        volumes:
          - name: glpi-data
            persistentVolumeClaim:
              claimName: glpi-data
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
- name: LABEL
  displayName: App label
  required: true
  #value: marketing-management-v1
